spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filehitory?serverTimezone=CTT
    username: root
    password: qq123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
